version: '3'
services:
  gateway_service:
    build:
      context: .
      dockerfile: ./gateway_service.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
  contract_service:
    build:
      context: .
      dockerfile: ./contract_service.Dockerfile
    ports:
      - "50051:50051"
    expose:
      - "50051"
  reservation_service:
    build:
      context: .
      dockerfile: ./reservation_service.Dockerfile
    ports:
      - "50052:50052"
    expose:
      - "50052"
