// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reservation.proto

package hellogrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReservationRequest struct {
	Quantity             int32    `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{0}
}

func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(m, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type ReservationReply struct {
	ReservationId        string   `protobuf:"bytes,1,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationReply) Reset()         { *m = ReservationReply{} }
func (m *ReservationReply) String() string { return proto.CompactTextString(m) }
func (*ReservationReply) ProtoMessage()    {}
func (*ReservationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b272c5347b2042, []int{1}
}

func (m *ReservationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationReply.Unmarshal(m, b)
}
func (m *ReservationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationReply.Marshal(b, m, deterministic)
}
func (m *ReservationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationReply.Merge(m, src)
}
func (m *ReservationReply) XXX_Size() int {
	return xxx_messageInfo_ReservationReply.Size(m)
}
func (m *ReservationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationReply proto.InternalMessageInfo

func (m *ReservationReply) GetReservationId() string {
	if m != nil {
		return m.ReservationId
	}
	return ""
}

func init() {
	proto.RegisterType((*ReservationRequest)(nil), "hellogrpc.ReservationRequest")
	proto.RegisterType((*ReservationReply)(nil), "hellogrpc.ReservationReply")
}

func init() { proto.RegisterFile("reservation.proto", fileDescriptor_c1b272c5347b2042) }

var fileDescriptor_c1b272c5347b2042 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4a, 0x2d, 0x4e,
	0x2d, 0x2a, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc,
	0x48, 0xcd, 0xc9, 0xc9, 0x4f, 0x2f, 0x2a, 0x48, 0x56, 0x32, 0xe0, 0x12, 0x0a, 0x42, 0xc8, 0x07,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71, 0x71, 0x14, 0x96, 0x26, 0xe6, 0x95, 0x64,
	0x96, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x4a, 0x16, 0x5c, 0x02, 0x28,
	0x3a, 0x0a, 0x72, 0x2a, 0x85, 0x54, 0xb8, 0x78, 0x91, 0x6c, 0xf1, 0x4c, 0x01, 0x6b, 0xe2, 0x0c,
	0x42, 0x15, 0x34, 0x0a, 0xe3, 0xe2, 0x46, 0xd2, 0x29, 0xe4, 0xce, 0xc5, 0x0e, 0xe1, 0xa6, 0x0a,
	0xc9, 0xea, 0xc1, 0x5d, 0xa4, 0x87, 0xe9, 0x1c, 0x29, 0x69, 0x5c, 0xd2, 0x05, 0x39, 0x95, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x5f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x1c, 0x60, 0x55,
	0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReservationClient is the client API for Reservation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReservationClient interface {
	Reserve(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationReply, error)
}

type reservationClient struct {
	cc *grpc.ClientConn
}

func NewReservationClient(cc *grpc.ClientConn) ReservationClient {
	return &reservationClient{cc}
}

func (c *reservationClient) Reserve(ctx context.Context, in *ReservationRequest, opts ...grpc.CallOption) (*ReservationReply, error) {
	out := new(ReservationReply)
	err := c.cc.Invoke(ctx, "/hellogrpc.Reservation/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServer is the server API for Reservation service.
type ReservationServer interface {
	Reserve(context.Context, *ReservationRequest) (*ReservationReply, error)
}

// UnimplementedReservationServer can be embedded to have forward compatible implementations.
type UnimplementedReservationServer struct {
}

func (*UnimplementedReservationServer) Reserve(ctx context.Context, req *ReservationRequest) (*ReservationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}

func RegisterReservationServer(s *grpc.Server, srv ReservationServer) {
	s.RegisterService(&_Reservation_serviceDesc, srv)
}

func _Reservation_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hellogrpc.Reservation/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).Reserve(ctx, req.(*ReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reservation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hellogrpc.Reservation",
	HandlerType: (*ReservationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _Reservation_Reserve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reservation.proto",
}
